### PR TITLE
Diagnostics: Audit and fix HIR Eval diagnostics

### LINKED ISSUE #124: Diagnostics: Audit and fix HIR Eval diagnostics

### PR DESCRIPTION
**Pull request by oana-barbu**

### CODE REVIEW

File: plankc/frontend/hir-eval/src/builtins.rs [hunk 1]
```diff
@@ -103,17 +103,14 @@ impl Scope<'_, '_> {
         if builtin.is_pure() {
             let folded = self.with_values_buf(|this, values_buf_offset| {
                 for &arg in args {
-                    let (state, arg_def_span) = this.bindings[arg]
+                    let (state, arg_def_loc) = this.bindings[arg]
```
Comment (Philogy) [inline plankc/frontend/hir-eval/src/builtins.rs]: why did you rename a span to loc?

File: plankc/frontend/hir-eval/src/scope.rs [hunk 2]
```diff
@@ -5,20 +5,38 @@ use plank_mir as mir;
 use plank_session::{EvmBuiltin, MaybePoisoned, Poisoned, SourceId, SourceSpan, SrcLoc, poison};
 use plank_values::{TypeId, Value, ValueId};
 
+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
+pub(crate) enum LocalLoc {
+    Inline(SrcLoc),
+    Ref { use_loc: SrcLoc, def_loc: SrcLoc },
+}
```
Comment (Philogy) [inline plankc/frontend/hir-eval/src/scope.rs]: I think this is unnecessarily large tbh (24 bytes I think), I made `DefOrigin` (8 bytes) for this purpose actually just didn't get around to updating it everywhere.

File: plankc/frontend/hir-eval/src/diagnostics.rs [hunk 3]
```diff
@@ -2,6 +2,11 @@ use plank_hir as hir;
 use plank_session::{builtins::builtin_names, diagnostic::fmt_count, *};
 use plank_values::TypeInterner;
 
+pub(crate) enum DiagnosticLoc {
+    Inline(SrcLoc),
+    CrossFile { use_loc: SrcLoc, def_loc: SrcLoc },
+}
```
Comment (Philogy) [inline plankc/frontend/hir-eval/src/diagnostics.rs]: I think you should find a better name for "DiagnosticLoc" and "CrossFile", it's more of an expression or value location/source, no? And it's not guaranteed to be cross file just because it has a def loc or is it? Like it could just be a `let` defined elsewhere, no?

File: plankc/frontend/hir-eval/src/evaluator.rs [hunk 4]
```diff
@@ -33,7 +33,7 @@ pub(crate) struct Evaluator<'a> {
 
     pub lowered_fns_cache: HashMap<ValueId, State<MaybePoisoned<mir::FnId>>>,
 
-    pub call_arg_spans: ListOfLists<CallArgSpansIdx, SourceSpan>,
+    pub call_arg_spans: ListOfLists<CallArgSpansIdx, SrcLoc>,
```
Comment (Philogy) [inline plankc/frontend/hir-eval/src/evaluator.rs]: no this is wrong! why do you need a per argument source id? they're all the same

File: plankc/frontend/hir-eval/src/functions.rs [hunk 5]
```diff
@@ -250,10 +266,11 @@ impl Scope<'_, '_> {
         idx: u32,
     ) {
         assert!(!comptime, "todo: comptime parameters");
-        let EvalContext::FunctionPreamble { call_scope_source, arg_spans } = self.ctx else {
+        let EvalContext::FunctionPreamble { arg_spans } = self.ctx else {
             unreachable!("invariant: param instr outside of fn preamable")
         };
 
+        let arg_loc = self.eval.call_arg_spans[arg_spans][idx as usize];
```
Comment (Philogy) [inline plankc/frontend/hir-eval/src/functions.rs]: yeah by removing `call_scope_source` you're forced to do the less efficient resolution by getting the data from the call arg spans array.
