### PR TITLE
🐞 fix to-SSA pass failing on certain inputs

### LINKED ISSUE #166: Backend Crashes On Ternary
Repro:

```
init {
    let mut a = 0;
    if a == 0 {
        let raw = @evm_caller();
        let tick = if raw > 0 { raw +% 1 } else { raw };
        a = tick;
    }
    @evm_stop();
}
```

### PR DESCRIPTION
**Pull request by Philogy**

### CODE REVIEW

File: plankc/frontend/cli/src/main.rs [hunk 1]
```diff
@@ -58,6 +58,12 @@ struct BuildArgs {
     #[arg(short = 'm', long = "show-mir", help = "show MIR")]
     show_mir: bool,
 
+    #[arg(long = "show-sir-in", help = "show SIR post `mir-lower`")]
```
Comment (oana-barbu) [inline plankc/frontend/cli/src/main.rs]: I find "in" and "last" vague. "post-mir" / "pre-bytecode" might be a bit wordy but they convey the idea better

File: plankc/sir/crates/passes/src/transforms/ssa_transform.rs [hunk 2]
```diff
@@ -1,470 +1,895 @@
...
+use crate::{AnalysesStore, Pass, Predecessors, run_pass, transforms::CriticalEdgeSplitting};
+use hashbrown::{HashMap, HashSet};
+use plank_core::{DenseIndexSet, Idx, IncIterable, IndexVec, Span};
+use sir_data::{BasicBlock, BasicBlockId, Control, ControlView, EthIRProgram, LocalId, index_vec};
+use smallvec::SmallVec;
+
+type Defs = IndexVec<BasicBlockId, HashMap<LocalId, LocalId>>;
 
-impl Pass for SsaTransform {
+// to-SSA is usually a one-off operation so need to try and cache state.
```
Comment (oana-barbu) [inline plankc/sir/crates/passes/src/transforms/ssa_transform.rs:7]: so NO need
